quartz:
    scheduler: 
        cron: 
          increase: 0 0 0/1 * * ?
          update: 0 0 0/1 * * ?
config: 
    #######同步工具(可选datax和sqoop)
    sync_tool: datax
    #######linux hive相关信息
    remote_ssh_ip: 127.0.0.1
    remote_ssh_user: root
    remote_ssh_pwd: ******
    
    #######datax JSON文件本地路径
    datax_local_path: D:/datax_config
    datax_job_dir: /root/datax/job
    
    #######linux服务器上datax_py路径
    datax_remote_path: /root/datax/bin/datax.py
    
    ######hadoop文件系统路径
    hadoop_dfs_path: /user/hive/warehouse
    
    #######datax的json文件模板(部署到linux环境时需要将文件拷贝至相关路劲并修改此参数为当前路劲)
    datax_json_template: D:/datax_cfg_template.json
    
    #########hive连接配置
    hive_url: jdbc:hive2://127.0.0.1:10000/yinian
    hive_username: root
    hive_password: ******
    hive_driver: org.apache.hive.jdbc.HiveDriver
    
    
    #########hive同步信息库连接配置
    hive_mysql_sync_url: jdbc:mysql://127.0.0.1:3306/hive_sync
    hive_mysql_sync_username: root
    hive_mysql_sync_password: ******
    hive_mysql_sync_driver: com.mysql.jdbc.Driver
    
    #####业务库信息
    bi_mysql_url_part: jdbc:mysql://127.0.0.1:3306/
    bi_mysql_username: biuser
    bi_mysql_password: ******
    bi_mysql_driver: com.mysql.jdbc.Driver
    bi_mysql_schema: yinian
    
    ######mysql内网地址
    bi_mysql_url_inner_ip: 127.0.0.1
    
    ######邮件信息
    from_mail_account: ******@qq.com
    from_mail_pwd: *******
    from_mail_smtp_host: smtp.qq.com
    to_mail_account: liumeng@test.com
    from_personal: 大数据同步平台
    to_personal: 尊敬的工程师
    
